endeavouros-team/endeavouros-i3wm-setup

.config/i3/config, .config/i3/i3blocks.conf, .config/i3/keybindings-rofi, .config/i3/scripts/rofi-shortcuts
Basic modification just for testing rofi as an alternative to xed to get information about shortcuts configurations.
Can be expanded to include software specific shortcuts, system aliases, special command and many more since if fast and it integrates well with i3; Let me know how it goes.
Cheers.
=> Added rofi-shortcuts as an alternative help menu

.config/rofi/powermenu.rasi, .config/rofi/rofidmenu.rasi
Remove non function syntax and add correct syntax
- **.config/rofi/powermenu.rasi**
Remove `fullscreen` and `hide-scrollbar` attribute from `configuration` section. Add `scrollbar : false` to `listview` section.
- **.config/rofi/rofidmenu.rasi**
Remove `fullscreen` and `hide-scrollbar` attribute from `configuration` section.
`fullscreen` and `hide-scrollbar` attribute in `configuration` section are not supported and Rofi throws warning if you use them.
=> Fix scrollbar syntax in rofi

.config/i3/config, .config/i3/i3blocks.conf, .config/i3/scripts/keyboard-switch.sh
This is my way to manage multiple keyboards (english + slovak) under i3.
In this example (when uncommented) switching between layouts is possible by pressing `Alt`+`CAPS`.
The current layout name is displayed in i3blocks.
=> add example how to manage multiple keyboard layouts under i3

.config/i3/scripts/battery.sh
Fixes #16 and `Wide character in print` message in STDERR.
In changes support for variable BLOCK_INSTANCE got lost and we always queried `battery_BAT0`.
=> fix Battery Charge display not working (#16)

.config/i3/config
**Additions:**
Added some optional settings and auto-start applications. (commented out)
Floating rule for "About" windows. (tested with Firefox and Thunderbird)
Links to documentation for compositors.
**Deletions:**
`#exec --no-startup-id picom -CGb`
Deleted picom's -C and -G parameters since they are deprecated. ([citation](https://man.archlinux.org/man/picom.1.en))
**Formatting:**
Moved some blocks around and placed them under headings.
Removed double empty line spaces.
=> i3 config: additions, deletions, formatting

.config/picom.conf
Added new missing setting, and removed old deprecated settings.
Created shadow exclusions to fix glitches with certain context menus.
**References:**
https://man.archlinux.org/man/picom.1.en
https://github.com/yshui/picom/blob/next/picom.sample.conf
https://github.com/yshui/picom/issues/748
https://github.com/yshui/picom/issues/435
`glx-no-stencil`
Missing description.
`use-damage`
New setting.
`glx-copy-from-front`
`dbe`
Deprecated settings.
`xrender-sync-fence`
Moved up.
=> updated picom.conf

.config/i3/scripts/keyhint, README.md, force-knowledge.md
`.config/i3/scripts/keyhint`
Fixed hotkey for keybinding helper which is set to F1 in config by default.
```
bindsym F1 exec ~/.config/i3/scripts/keyhint-2
```
`README.md`
Updated instructions for **dex** and **arandr** since they are are now enabled by default.
`force-knowledge.md`
Updated exec path of **force-knowledge.md** and **picom**.
Revised instructions to optionally disable **dex**.
=> a few small corrections

.config/i3/scripts/powermenu
Pretty self explanatory from title.
I had this problem on my own recent install a few days ago, but I also looked in the repo code here to make sure the problem wasn't the result of a local change on my machine, and indeed the power menu script has a bad reference to the blur lock script.
P.S.: Really been enjoying Endeavour and i3 (first time for both), so thanks!
=> Fix blur lock reference in power menu

.config/i3/config
Add suggestion for clipboard manager for rofi using `rofi-greenclip` from the AUR.
=> Clipboard manager for rofi

.config/rofi/power-profiles.rasi, .config/rofi/powermenu.rasi
I saw in the `powermenu.rasi` file a setting that was set twice in the `window` block. I decided to check (quickly) all the rofi files and deleted 1 attribute in :
- `powermenu.rasi`
- `power-profiles.rasi`
=> Rofi: remove redundant settings

.config/rofi/power-profiles.rasi, .config/rofi/powermenu.rasi, .config/rofi/rofidmenu.rasi, .config/rofi/rofikeyhint.rasi
Upon doing a fresh install of Endavour I took to comparing my dotfiles/config to the defaults to see what the changes were, but what I found was a bit of a mess.
A mixture of tabs and spaces were used, an attempt at value alignment was made for some properties but ignored for others, extra spacing in places, etc. This should correct all of that.
Hopefully this looks alright to all. I noticed some blocks (like `configuration`) typically had way more spacing than others, which I removed for consistency's sake. Not sure if that was intended or just incidental.
=> style: Correct formatting inconsistencies in rofi config

README.md
Confusing to have two commands in the same line. Users are running them together.
=> Fix minor formatting error

force-knowledge.md
Added a / in the link to the default configs to make the command work
=> Fix typo in command to restore i3 default settings

i3_install
as dbus-launch fails, if there is no xed.dconf, it has to be copied to home dir first
=> copy xed.dconf to home in i3_install script

.config/i3/scripts/power-profiles, .config/i3/scripts/powermenu
Fixes the infinite loading cursor on empty screen areas after locking from powermenu & selecting power modes
=> Update powermenu - loading cursor bug

.config/i3/config
This adds a keybinding for muting/unmuting the mic. Useful for laptops that have a dedicated key.
=> add mute mic keybinding

.config/i3/scripts/volume_brightness.sh
Missing the -get flag from xbacklight to work with the regex.
=> [volume_brightness.sh] Missing brightness current value

etc/skel/.config/i3/scripts/memory
The CPU script in this same directory will display as such on the i3status: `09%` - while the memory status doesn't pad with a `0`, so it'll look like this by default `9%`. This fixes the script to pad with a `0` by default so the style is unified.
=> Fix memory status/percentage display

etc/skel/.config/i3/config
Apologies if this is intended functionality, but I didn't see that stated anywhere. 
This change makes it so that switching workspaces with the numpad works the same regardless of the state of numlock. 
Previously, if numlock was off then $mod + Numpad 1 would go to workspace 1 and not `$ws1`  while if numlock was on the $mod + Numpad 1 would go to `$ws1`.  This is confusing as if you cycle between having numlock on/off a lot then you'll go to different workspaces. 
Now, it has been updated so that $mod + Numpad 1 goes to `$ws1` when numlock is off.
(`$ws1` was an example, this functionality extends for all default workspace variables)
=> Make numpad keys work similarly for switching workspaces when numlock is on or off

etc/skel/.config/i3/config
edited the line 
bindsym XF86AudioPlay exec --no-startup-id playerctl play
to be:
bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause 
And deleted the variant of the first line with pause entirely.
This is my first pull request ever, sorry for any hiccups.
=> Fixed playerctl pause and play not working

etc/skel/.config/i3/scripts/ppd-status
I modified the ppd-status script so I could display 'tags' instead the name of each `power-profiles-daemon` profile name. I think this looks more clean and adds functionality to display a translation for each name or a custom tag:
Edit: if ther's no 'tag' assgined to the current profile, it will just display the ppd profile name.
=> Adding tags / translation functionality to the i3block displaying the current power profile

i3_install
A very simple cleanup to remove some trailing spaces found in i3_install.
=> Remove trailing spaces in i3_install

etc/skel/.config/dunst/dunstrc
For some reason, after my most recent OS update, the notification heights for dunst were maxed at the 300 height. Changing the height to (0, 300) fixes it however.
When starting dunst from the command line, it gave a warning:
`Using legacy offset syntax NxN, you should switch to the new syntax (N, N)`
I updated offset to the hew standard.
- fixed a typo in line one.
=> Updated height and offset settings.
